Repository Team-TTT/Circle-BE, pull requests merged in 2022-10, with the labels that each got.

#1 docs: pr 관련 파일 생성
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: docs, review-required

#3 Setting/logger
  .gitignore
  app.js
  bin/www
  lib/logger.js
  package-lock.json
  package.json
Labels: feat, review-required

#4 Setting/init/express
  .eslintignore
  .eslintrc.js
  .gitignore
  .husky/pre-commit
  README.md
  app.js
  bin/www
  lib/logger.js
  package-lock.json
  package.json
  prettier.config.js
  routes/index.js
Labels: feat, review-required

#5 feat: 프로젝트 디렉토리 구조 설정 및 mongoose 세팅
  .env.sample
  .eslintrc.js
  app.js
  bin/www
  index.js
  libs/logger.js
  package-lock.json
  package.json
  src/loaders/database.js
  src/loaders/index.js
  src/loaders/server.js
  src/routes/index.js
Labels: feat, review-required

#6 feat: 토큰 검증 미들웨어 추가
  package-lock.json
  package.json
  src/constants/MESSAGE.js
  src/loaders/index.js
  src/routes/middleware/verifyToken.js
Labels: feat, review-required

#7 Feature/db schema
  .env.sample
  .eslintignore
  models/Channel.js
  models/Project.js
  models/User.js
  src/loaders/database.js
Labels: feat, review-required

#8 feat: /users POST API 구현
  .eslintrc.js
  src/constants/MESSAGE.js
  src/loaders/index.js
  src/routes/controllers/user.controller.js
  src/routes/index.js
  src/routes/middleware/verifyToken.js
  src/routes/user.route.js
Labels: feat, review-required

#9 feat: socket 서버 추가
  .eslintignore
  package-lock.json
  package.json
  src/constants/CHANNEL.js
  src/loaders/database.js
  src/loaders/index.js
  src/loaders/server.js
  src/loaders/socket.js
  src/utils/fp.js
Labels: feat, review-required

#10 feat: /projects API POST 구현 완료
  .env.sample
  .github/pull_request_template.md
  models/Project.js
  package.json
  src/constants/CHANNEL.js
  src/constants/MESSAGE.js
  src/constants/index.js
  src/loaders/socket.js
  src/routes/controllers/project.controller.js
  src/routes/controllers/user.controller.js
  src/routes/index.js
  src/routes/middleware/verifyToken.js
  src/routes/project.route.js
  src/utils/crypto.js
Labels: feat, review-required

#13 [2022.10.19] feat: /auth API 구현 완료
  .env.sample
  .gitignore
  configs/firebase.config.js
  package-lock.json
  package.json
  src/loaders/index.js
  src/routes/auth.route.js
  src/routes/controllers/auth.controller.js
  src/routes/index.js
  src/routes/middleware/createSessionCookie.js
  src/routes/middleware/setResponseHeader.js
  src/routes/middleware/verifyToken.js
  src/routes/project.route.js
  src/routes/user.route.js
Labels: feat, review-required

#11 [2022.10.19] feat: /projects/:projectId Delete Api 구현 완료
  src/constants/index.js
  src/loaders/index.js
  src/routes/auth.route.js
  src/routes/controllers/auth.controller.js
  src/routes/controllers/project.controller.js
  src/routes/project.route.js
Labels: feat, review-required

#12 [2022.10.19] feat: /projects/projectId Put Api 구현 완료
  package.json
  src/loaders/index.js
  src/routes/controllers/project.controller.js
  src/routes/index.js
  src/routes/service.route.js
Labels: feat, review-required

#14 [2022.10.19] feat: projects get api 구현
  .eslintrc.js
  models/User.js
  package-lock.json
  prettier.config.js
  src/constants/index.js
  src/routes/controllers/project.controller.js
  src/routes/project.route.js
  src/routes/service.route.js
Labels: feat, review-required

#15 [2022.10.20] Feature/projects/:projectId GET api 구현
  .gitignore
  config/firebase.config.js
  package-lock.json
  package.json
  src/routes/auth.route.js
  src/routes/controllers/auth.controller.js
  src/routes/controllers/project.controller.js
  src/routes/index.js
  src/routes/middlewares/createSessionCookie.js
  src/routes/middlewares/setResponseHeader.js
  src/routes/middlewares/verifyToken.js
  src/routes/project.route.js
Labels: feat, review-required

#16 refacor: 로그인 플로우 변경
  .gitignore
  models/Project.js
  models/User.js
  src/loaders/database.js
  src/loaders/index.js
  src/loaders/server.js
  src/loaders/socket.js
  src/routes/controllers/auth.controller.js
  src/routes/controllers/project.controller.js
  src/routes/index.js
  src/routes/middlewares/setResponseServiceHeader.js
Labels: refactor, review-required

#17 [2022.10.22] refactor: Schema feild명 변경에 따른 수정 및 req.user 활용
  .github/pull_request_template.md
  .gitignore
  models/Project.js
  models/User.js
  src/loaders/index.js
  src/routes/controllers/auth.controller.js
  src/routes/controllers/project.controller.js
  src/routes/index.js
  src/routes/middlewares/verifyToken.js
  src/routes/service.route.js
Labels: refactor, review-required

#18 [2022.10.23] refactor: user 정보 받는 방법 변경
  models/User.js
  src/routes/controllers/auth.controller.js
  src/routes/middlewares/verifyToken.js
Labels: refactor, review-required

#20 [2022.10.23] feat: channels put api
  package.json
  src/routes/controllers/channel.controller.js
  src/routes/project.route.js
Labels: feat, review-required

#22 [2022.10.23] feat: projects/:projectId/channels/:channelId delete api
  package.json
  src/routes/controllers/channel.controller.js
  src/routes/project.route.js
Labels: feat, review-required

#21 [2022.10.23] feat: 클라이언트와의 소켓 송신을 위한 singal-server 구현 완료
  package-lock.json
  package.json
  src/constants/index.js
  src/loaders/socket.js
  src/loaders/socket/controller.js
  src/loaders/socket/index.js
  src/utils/fp.js
Labels: feat, review-required

#23 [2022.10.24] feat: projects/:projectId/service/auth post api
  package.json
  src/routes/controllers/auth.controller.js
  src/routes/controllers/channel.controller.js
  src/routes/controllers/project.controller.js
  src/routes/index.js
  src/routes/service.route.js
Labels: feat, refactor, review-required

#24 refactor: 프론트와 연결작업시 생기는 오류 수정
  package.json
  src/routes/controllers/auth.controller.js
  src/routes/controllers/project.controller.js
  src/routes/middlewares/setResponseHeader.js
  src/routes/middlewares/verifyToken.js
Labels: refactor, review-required

#25 refactor: 소켓 경로가 추가되었습니다
  package.json
  src/loaders/socket/index.js
Labels: refactor, review-required

#26 [2022.10.27] refactor: api 동작 관련 일부 잘못된 부분 수정 및 cors, httponly 설정 변경
  package.json
  src/routes/controllers/auth.controller.js
  src/routes/controllers/channel.controller.js
  src/routes/controllers/project.controller.js
  src/routes/middlewares/createSessionCookie.js
  src/routes/middlewares/setResponseHeader.js
Labels: refactor, review-required
